--- #YAML:1.0
name:               POE-Filter-SSL
version:            0.27
abstract:           The easiest and flexiblest way to SSL in POE!
author:
    - Markus Schraeder <privi@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Status:         0
    Net::SSLeay:          1.32
    POE::Filter::HTTPD:   0
    POE::Filter::Stackable:  0
    POE::Wheel::ReadWrite:  0
    Test::More:           0
    XSLoader:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
